---
# tasks file for ntp-ansible-role

- name: ntp mode Specific Variables
  include_vars: "{{ ntp_mode }}.yml"

- name: ntp is installed
  apt: pkg=ntp state=installed

- name: ntp is configured
  template: src=ntp.conf.j2 dest=/etc/ntp.conf

- name: ntp is restarted and enabled
  service: name=ntp state=restarted enabled=yes