---
# tasks file for ntp-ansible-role

- name: ntp mode Specific Variables
  include_vars: "{{ ntp_mode }}.yml"

# OS Specific packages
- include: 'Ubuntu.yml'
  when: ansible_distribution == 'Ubuntu'

- include: 'FreeBSD.yml'
  when: ansible_distribution == 'FreeBSD'

- name: ntp is configured
  template: src="ntp-{{ ntp_mode }}.conf.j2" dest="/etc/ntp.conf"

- name: ntp is restarted and enabled
  service: name=ntp state=restarted enabled=yes