---
# tasks file for ntp-ansible-role

- debug: msg="{{ ansible_distribution }}"

- name: OS Specific Variables
  include_vars: "{{ ansible_distribution }}.yml"

- name: ntp mode Specific Variables
  include_vars: "{{ ntp_mode }}.yml"

# OS Specific packages
- include: 'Ubuntu.yml'
  when: ansible_distribution == 'Ubuntu'

- include: 'FreeBSD.yml'
  when: ansible_distribution == 'FreeBSD'

- name: ntp is configured
  template: src="ntp-{{ ntp_mode }}.conf.j2" dest=/etc/ntp.conf

- copy: src=dns.py dest=/root/dns.py mode=0550 owner=root

- name: ntp is restarted and enabled
  service: name={{ ntp_service }} state=restarted enabled=yes