---
# tasks file for ntp-ansible-role

- name: ntp mode Specific Variables
  include_vars: "{{ ntp_mode }}.yml"

- name: ntp is installed
  apt: pkg={{ ntp_package }} state=installed

- name: ntp is configured
  template: src="ntp-{{ ntp_mode }}.conf.j2" dest=/etc/ntp.conf

- name: ntp is restarted and enabled
  service: name={{ ntp_package }} state=restarted enabled=yes